### Test Join

In [2]:
# Imports for pytorch
import numpy as np
import matplotlib
from matplotlib import pyplot as plt
import scipy
import sklearn
import pandas as pd

In [2]:
bfb_ts_data = pd.read_csv("BFB_SP23_TS.csv")
bfb_ts_data = bfb_ts_data.drop("Notes",axis=1)
bfb_ts_data['Date'] = pd.to_datetime(bfb_ts_data['Date'])
bfb_ts_data = bfb_ts_data.applymap(lambda x: x.strip() if isinstance(x, str) else x)
bfb_ts_data

,Transect #,Date,Route,Time Bin,Species,# Individuals
0,1,2023-02-21,C,Evening (3-5pm),Anna's Hummingbird,2
1,1,2023-02-21,C,Evening (3-5pm),Turkey Vulture,1
2,1,2023-02-21,C,Evening (3-5pm),Black Phoebe,1
3,1,2023-02-21,C,Evening (3-5pm),American Crow,4
4,1,2023-02-21,C,Evening (3-5pm),Oak Titmouse,1
...,...,...,...,...,...,...
247,24,2023-04-26,A,Evening (3-5pm),Red-Shouldered Hawk,1
248,24,2023-04-26,A,Evening (3-5pm),American Crow,5
249,24,2023-04-26,A,Evening (3-5pm),Bushtit,3
250,24,2023-04-26,A,Evening (3-5pm),Lesser Goldfinch,5
251,24,2023-04-26,A,Evening (3-5pm),Dark-eyed Junco,2

In [3]:
bfb_tp_data = pd.read_csv("BFB_SP23_TP.csv")
bfb_tp_data = bfb_tp_data.drop("Notes",axis=1)
bfb_tp_data['Date'] = pd.to_datetime(bfb_tp_data['Date'])
bfb_tp_data = bfb_tp_data.applymap(lambda x: x.strip() if isinstance(x, str) else x)
bfb_tp_data

,Transect #,Date,Route,Time Bin,Observer(s),Start Time,End Time,Weather,Precipitation,Wind,Temperature,eBird Link
0,1,2023-02-21,C,Evening (3-5pm),"Allison Olvera, Zebedee Cataag, Richard Hasega...",15:19,15:37,Sunny,Dry,Windy,52,https://ebird.org/checklist/S129322949
1,2,2023-02-21,B,Evening (3-5pm),"Allison Olvera, Zebedee Cataag, Richard Hasega...",15:37,16:07,Sunny,Dry,Windy,52,https://ebird.org/checklist/S129326008
2,5,2023-03-01,C,Evening (3-5pm),"Allison Olvera, Diego Montesinos, Miguel Gomez...",15:31,15:58,Sunny,Dry,Slight Wind,52,https://ebird.org/checklist/S129954473
3,6,2023-03-05,A,Evening (3-5pm),"Isha Murali, Carter (Dog), Sierra Glassman, Pe...",15:18,15:59,Partial Cloudy,Dry,Slight Wind,50,https://ebird.org/checklist/S130286897
4,7,2023-03-08,B,Mid-day (11am-1pm),"Pearl Lee, Allison Olvera",12:07,12:53,Sunny,Dry,Calm,45,https://ebird.org/checklist/S130471678
5,8,2023-03-09,C,Mid-day (11am-1pm),Pearl Lee,11:04,11:27,Cloudy,Dry,Slight Wind,43,https://ebird.org/checklist/S130532762
6,9,2023-03-10,B,Mid-day (11am-1pm),"Cecilia Mendoza, Sierra Glassman",11:10,11:25,Cloudy,Dry,Calm,51,https://ebird.org/checklist/S130600681
7,10,2023-03-11,C,Morning (7-9am),Sierra Glassman,8:51,9:00,Cloudy,Dry,Calm,51,https://ebird.org/checklist/S130664727
8,11,2023-03-15,B,Mid-day (11am-1pm),"Aaron Guo, Jonathan Lee, Sierra Glassman, Pear...",12:39,13:00,Sunny,Dry,Slight Wind,54,https://ebird.org/checklist/S130986004
9,12,2023-03-21,B,Mid-day (11am-1pm),Pearl Lee,11:09,11:25,Cloudy,Rain,Windy,51,https://ebird.org/checklist/S131466521
10,13,2023-03-22,C,Mid-day (11am-1pm),Pearl Lee,12:08,12:28,Cloudy,Drizzle,NaN,46,https://ebird.org/checklist/S131547348
11,14,2023-03-23,B,Mid-day (11am-1pm),"Pearl Lee, Emily Banno, Emma Paradise, Kira Wi...",11:14,11:40,Partial Cloudy,Dry,Slight Wind,46,https://ebird.org/checklist/S131617714
12,15,2023-03-25,C,Mid-day (11am-1pm),Sierra Glassman,11:00,11:18,Sunny,Dry,Slight Wind,48,https://ebird.org/checklist/S131691837
13,16,2023-03-25,A,Mid-day (11am-1pm),Sierra Glassman,11:24,11:46,Sunny,Dry,Calm,49,https://ebird.org/checklist/S131694003
14,17,2023-04-05,B,Mid-day (11am-1pm),Pearl Lee,12:10,12:33,Sunny,Dry,Calm,40,https://ebird.org/checklist/S132790867
15,18,2023-04-05,A,Mid-day (11am-1pm),"Kristina Twaalfhoven, Megan Tandean, Sierra Gl...",12:16,12:42,Sunny,Dry,Slight Wind,55,https://ebird.org/checklist/S132791703
16,19,2023-04-14,A,Mid-day (11am-1pm),"Zebedee Cataag, Vishal Subramanyan, Jonathan L...",12:05,12:29,Sunny,Dry,Slight Wind,56,https://ebird.org/checklist/S133733803
17,20,2023-04-14,C,Mid-day (11am-1pm),"Zebedee Cataag, Vishal Subramanyan, Jonathan L...",12:34,12:54,Sunny,Dry,Slight Wind,56,https://ebird.org/checklist/S133736316
18,21,2023-04-18,A,Evening (3-5pm),"Sierra Glassman, Aaron Guo, Shiraz Lal",15:00,15:30,Sunny,Dry,Calm,54,https://ebird.org/checklist/S134225392
19,22,2023-04-23,A,Mid-day (11am-1pm),Sierra Glassman,11:19,11:41,Sunny,Dry,Slight Wind,62,https://ebird.org/checklist/S134759544
20,23,2023-04-23,B,Mid-day (11am-1pm),Sierra Glassman,11:48,12:12,Sunny,Dry,Slight Wind,62,https://ebird.org/checklist/S134763833
21,24,2023-04-26,A,Evening (3-5pm),"Vishal Subramanyan, Sierra Glassman",15:33,15:48,Sunny,Dry,Calm,75,https://ebird.org/checklist/S135118635

In [4]:
bfb_tp_times = bfb_tp_data[["Transect #","Date","Start Time","End Time"]]
bfb_tp_times

    Transect #       Date Start Time End Time
0            1 2023-02-21      15:19    15:37
1            2 2023-02-21      15:37    16:07
2            5 2023-03-01      15:31    15:58
3            6 2023-03-05      15:18    15:59
4            7 2023-03-08      12:07    12:53
5            8 2023-03-09      11:04    11:27
6            9 2023-03-10      11:10    11:25
7           10 2023-03-11       8:51     9:00
8           11 2023-03-15      12:39    13:00
9           12 2023-03-21      11:09    11:25
10          13 2023-03-22      12:08    12:28
11          14 2023-03-23      11:14    11:40
12          15 2023-03-25      11:00    11:18
13          16 2023-03-25      11:24    11:46
14          17 2023-04-05      12:10    12:33
15          18 2023-04-05      12:16    12:42
16          19 2023-04-14      12:05    12:29
17          20 2023-04-14      12:34    12:54
18          21 2023-04-18      15:00    15:30
19          22 2023-04-23      11:19    11:41
20          23 2023-04-23      11:48    12:12
21          24 2023-04-26      15:33    15:48

In [5]:
bfb_tp_times.dtypes

Transect #             int64
Date          datetime64[ns]
Start Time            object
End Time              object
dtype: object

In [6]:
bfb_ts_data.dtypes

Transect #                int64
Date             datetime64[ns]
Route                    object
Time Bin                 object
Species                  object
# Individuals             int64
dtype: object

In [7]:
bfb_ts_data.merge(bfb_tp_times,on="Transect #")

,Transect #,Date_x,Route,Time Bin,Species,# Individuals,Date_y,Start Time,End Time
0,1,2023-02-21,C,Evening (3-5pm),Anna's Hummingbird,2,2023-02-21,15:19,15:37
1,1,2023-02-21,C,Evening (3-5pm),Turkey Vulture,1,2023-02-21,15:19,15:37
2,1,2023-02-21,C,Evening (3-5pm),Black Phoebe,1,2023-02-21,15:19,15:37
3,1,2023-02-21,C,Evening (3-5pm),American Crow,4,2023-02-21,15:19,15:37
4,1,2023-02-21,C,Evening (3-5pm),Oak Titmouse,1,2023-02-21,15:19,15:37
...,...,...,...,...,...,...,...,...,...
247,24,2023-04-26,A,Evening (3-5pm),Red-Shouldered Hawk,1,2023-04-26,15:33,15:48
248,24,2023-04-26,A,Evening (3-5pm),American Crow,5,2023-04-26,15:33,15:48
249,24,2023-04-26,A,Evening (3-5pm),Bushtit,3,2023-04-26,15:33,15:48
250,24,2023-04-26,A,Evening (3-5pm),Lesser Goldfinch,5,2023-04-26,15:33,15:48
251,24,2023-04-26,A,Evening (3-5pm),Dark-eyed Junco,2,2023-04-26,15:33,15:48

In [8]:
bfb_ts_data

,Transect #,Date,Route,Time Bin,Species,# Individuals
0,1,2023-02-21,C,Evening (3-5pm),Anna's Hummingbird,2
1,1,2023-02-21,C,Evening (3-5pm),Turkey Vulture,1
2,1,2023-02-21,C,Evening (3-5pm),Black Phoebe,1
3,1,2023-02-21,C,Evening (3-5pm),American Crow,4
4,1,2023-02-21,C,Evening (3-5pm),Oak Titmouse,1
...,...,...,...,...,...,...
247,24,2023-04-26,A,Evening (3-5pm),Red-Shouldered Hawk,1
248,24,2023-04-26,A,Evening (3-5pm),American Crow,5
249,24,2023-04-26,A,Evening (3-5pm),Bushtit,3
250,24,2023-04-26,A,Evening (3-5pm),Lesser Goldfinch,5
251,24,2023-04-26,A,Evening (3-5pm),Dark-eyed Junco,2

In [3]:
test_dataset = pd.read_csv("BFB_SP23_TP.csv")
test_dataset = test_dataset.applymap(lambda x: x.strip() if isinstance(x, str) else x)
test_dataset

,Transect #,Date,Route,Time Bin,Observer(s),Start Time,End Time,Weather,Precipitation,Wind,Temperature,eBird Link,Notes
0,1,02/21/2023,C,Evening (3-5pm),"Allison Olvera, Zebedee Cataag, Richard Hasega...",15:19,15:37,Sunny,Dry,Windy,52,https://ebird.org/checklist/S129322949,23mph wind
1,2,02/21/2023,B,Evening (3-5pm),"Allison Olvera, Zebedee Cataag, Richard Hasega...",15:37,16:07,Sunny,Dry,Windy,52,https://ebird.org/checklist/S129326008,NaN
2,5,03/01/2023,C,Evening (3-5pm),"Allison Olvera, Diego Montesinos, Miguel Gomez...",15:31,15:58,Sunny,Dry,Slight Wind,52,https://ebird.org/checklist/S129954473,NaN
3,6,03/05/2023,A,Evening (3-5pm),"Isha Murali, Carter (Dog), Sierra Glassman, Pe...",15:18,15:59,Partial Cloudy,Dry,Slight Wind,50,https://ebird.org/checklist/S130286897,NaN
4,7,03/08/2023,B,Mid-day (11am-1pm),"Pearl Lee, Allison Olvera",12:07,12:53,Sunny,Dry,Calm,45,https://ebird.org/checklist/S130471678,NaN
5,8,03/09/2023,C,Mid-day (11am-1pm),Pearl Lee,11:04,11:27,Cloudy,Dry,Slight Wind,43,https://ebird.org/checklist/S130532762,Rain started 11:19
6,9,03/10/2023,B,Mid-day (11am-1pm),"Cecilia Mendoza, Sierra Glassman",11:10,11:25,Cloudy,Dry,Calm,51,https://ebird.org/checklist/S130600681,NaN
7,10,03/11/2023,C,Morning (7-9am),Sierra Glassman,8:51,9:00,Cloudy,Dry,Calm,51,https://ebird.org/checklist/S130664727,NaN
8,11,03/15/2023,B,Mid-day (11am-1pm),"Aaron Guo, Jonathan Lee, Sierra Glassman, Pear...",12:39,13:00,Sunny,Dry,Slight Wind,54,https://ebird.org/checklist/S130986004,NaN
9,12,03/21/2023,B,Mid-day (11am-1pm),Pearl Lee,11:09,11:25,Cloudy,Rain,Windy,51,https://ebird.org/checklist/S131466521,NaN
10,13,03/22/2023,C,Mid-day (11am-1pm),Pearl Lee,12:08,12:28,Cloudy,Drizzle,NaN,46,https://ebird.org/checklist/S131547348,drizzle stopped 12:18
11,14,03/23/2023,B,Mid-day (11am-1pm),"Pearl Lee, Emily Banno, Emma Paradise, Kira Wi...",11:14,11:40,Partial Cloudy,Dry,Slight Wind,46,https://ebird.org/checklist/S131617714,Tree removal + loud noises near B6. Fallen tre...
12,15,03/25/2023,C,Mid-day (11am-1pm),Sierra Glassman,11:00,11:18,Sunny,Dry,Slight Wind,48,https://ebird.org/checklist/S131691837,NaN
13,16,03/25/2023,A,Mid-day (11am-1pm),Sierra Glassman,11:24,11:46,Sunny,Dry,Calm,49,https://ebird.org/checklist/S131694003,Lots of loud construction across campus
14,17,04/05/2023,B,Mid-day (11am-1pm),Pearl Lee,12:10,12:33,Sunny,Dry,Calm,40,https://ebird.org/checklist/S132790867,NaN
15,18,04/05/2023,A,Mid-day (11am-1pm),"Kristina Twaalfhoven, Megan Tandean, Sierra Gl...",12:16,12:42,Sunny,Dry,Slight Wind,55,https://ebird.org/checklist/S132791703,Landscaping and construction
16,19,04/14/2023,A,Mid-day (11am-1pm),"Zebedee Cataag, Vishal Subramanyan, Jonathan L...",12:05,12:29,Sunny,Dry,Slight Wind,56,https://ebird.org/checklist/S133733803,NaN
17,20,04/14/2023,C,Mid-day (11am-1pm),"Zebedee Cataag, Vishal Subramanyan, Jonathan L...",12:34,12:54,Sunny,Dry,Slight Wind,56,https://ebird.org/checklist/S133736316,Loud drumming from Sather Gate
18,21,04/18/2023,A,Evening (3-5pm),"Sierra Glassman, Aaron Guo, Shiraz Lal",15:00,15:30,Sunny,Dry,Calm,54,https://ebird.org/checklist/S134225392,NaN
19,22,04/23/2023,A,Mid-day (11am-1pm),Sierra Glassman,11:19,11:41,Sunny,Dry,Slight Wind,62,https://ebird.org/checklist/S134759544,NaN
20,23,04/23/2023,B,Mid-day (11am-1pm),Sierra Glassman,11:48,12:12,Sunny,Dry,Slight Wind,62,https://ebird.org/checklist/S134763833,NaN
21,24,04/26/2023,A,Evening (3-5pm),"Vishal Subramanyan, Sierra Glassman",15:33,15:48,Sunny,Dry,Calm,75,https://ebird.org/checklist/S135118635,NaN

In [6]:
temp_3 = test_dataset["Date"] +" "+ test_dataset["Start Time"]

In [7]:
import datetime

In [9]:
pd.to_datetime(temp_3)

0    2023-02-21 15:19:00
1    2023-02-21 15:37:00
2    2023-03-01 15:31:00
3    2023-03-05 15:18:00
4    2023-03-08 12:07:00
5    2023-03-09 11:04:00
6    2023-03-10 11:10:00
7    2023-03-11 08:51:00
8    2023-03-15 12:39:00
9    2023-03-21 11:09:00
10   2023-03-22 12:08:00
11   2023-03-23 11:14:00
12   2023-03-25 11:00:00
13   2023-03-25 11:24:00
14   2023-04-05 12:10:00
15   2023-04-05 12:16:00
16   2023-04-14 12:05:00
17   2023-04-14 12:34:00
18   2023-04-18 15:00:00
19   2023-04-23 11:19:00
20   2023-04-23 11:48:00
21   2023-04-26 15:33:00
dtype: datetime64[ns]